version: '2'
services:
    iotapp-app:
        image: iotapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://iotapp-postgresql:5432/IoTApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    iotapp-postgresql:
        extends:
            file: postgresql.yml
            service: iotapp-postgresql
